<template>
  <div class="background">
    <Navbar></Navbar>
    <div class="container vh-100">
      <div
        class="h-100 justify-content-center d-flex align-items-center flex-column"
      >
        <p class="text-light name text-focus-in">
          GABRIEL BARRETO<span class="end-point">.</span>
        </p>

        <a
          class="typewrite job-title"
          style="text-decoration: none"
          data-period="2000"
          data-type='[ "Engenheiro da Computação.", "Desenvolvedor Fullstack.", "Desenvolvedor Mobile."]'
        >
          <span class="wrap"></span>
        </a>
      </div>
      <div class="container text-center" style="margin-top: -12%">
        <div class="row">
          <div class="col align-self-center">
            <p class="text-light m-0 p-0">
              Deslize para descobrir mais sobre mim e oque faço
            </p>
            <font-awesome-icon
              class="animated-chevron-down bounce arrow-down"
              icon="fa-solid fa-chevron-down"
            />
          </div>
        </div>
      </div>
    </div>
    <div class="vh-100">
      <div
        class="h-100 justify-content-center d-flex align-items-center flex-column"
      >
        <p class="text-light name">GABRIEL BARRETO</p>
        <p class="text-light job-title">Engenheiro da Computação</p>
        <p class="text-light">Desenvolvedor Frontend e Mobile</p>
      </div>
    </div>
  </div>
</template>
<script src="./index.js"></script>
<style scoped>
.name {
  font-size: 10vh;
  font-weight: 600;
}
.job-title {
  font-size: 5vh;
  padding: 0;
  margin: 0;
  color: white;
}
.end-point {
  color: #c044ec;
}
.arrow-down {
  color: #c044ec;
  margin-top: 2%;
}
/* Animaçoes */
.text-focus-in {
  -webkit-animation: text-focus-in 1s
    cubic-bezier(0.55, 0.085, 0.68, 0.53) both;
  animation: text-focus-in 1s cubic-bezier(0.55, 0.085, 0.68, 0.53)
    both;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-9-1 12:9:36
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation text-focus-in
 * ----------------------------------------
 */
@-webkit-keyframes text-focus-in {
  0% {
    -webkit-filter: blur(12px);
    filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0px);
    filter: blur(0px);
    opacity: 1;
  }
}
@keyframes text-focus-in {
  0% {
    -webkit-filter: blur(12px);
    filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0px);
    filter: blur(0px);
    opacity: 1;
  }
}

/* Seta de deslizar */

.animated-chevron-down {
  -webkit-animation-duration: 2s;
  animation-duration: 2s;
  -webkit-animation-fill-mode: both;
  animation-fill-mode: both;
  animation-iteration-count: infinite;
}
@-webkit-keyframes bounce {
  0%,
  20%,
  50%,
  80%,
  100% {
    -webkit-transform: translateY(0);
  }
  40% {
    -webkit-transform: translateY(-25px);
  }
  60% {
    -webkit-transform: translateY(-10px);
  }
}

@keyframes bounce {
  0%,
  20%,
  50%,
  80%,
  100% {
    transform: translateY(0);
  }
  40% {
    transform: translateY(-25px);
  }
  60% {
    transform: translateY(-10px);
  }
}

.bounce {
  -webkit-animation-name: bounce;
  animation-name: bounce;
}
</style>
